<?php

declare(strict_types=1);

namespace App\Services;

/**
 * Loads and provides dancer data from the JSON files generated by the scraper.
 *
 * All data is read once per request and cached in-memory on the instance.
 * The data/ directory sits one level above the Laravel web/ directory.
 */
class DataService
{
    private const DIVISIONS = ['CHA', 'ALS', 'ADV', 'INT', 'NOV', 'NEW'];

    // Division order: index 0 = highest (CHA)
    private const DIV_ORDER = ['CHA' => 0, 'ALS' => 1, 'ADV' => 2, 'INT' => 3, 'NOV' => 4, 'NEW' => 5];

    private string $dataDir;
    private ?array $dancers = null;

    public function __construct()
    {
        $this->dataDir = dirname(base_path()) . '/data';
    }

    // -----------------------------------------------------------------------
    // Public API
    // -----------------------------------------------------------------------

    /** @return array<int,array> All dancers keyed by wscid */
    public function all(): array
    {
        if ($this->dancers === null) {
            $path = $this->dataDir . '/dancers.json';
            $this->dancers = file_exists($path)
                ? (json_decode(file_get_contents($path), true) ?? [])
                : [];
        }

        return $this->dancers;
    }

    /** Single dancer by wscid, or null if not found. */
    public function find(int $wscid): ?array
    {
        return $this->all()[(string) $wscid] ?? null;
    }

    /**
     * Full raw API data for a dancer (includes per-competition history).
     */
    public function rawData(int $wscid): ?array
    {
        $path = $this->dataDir . '/raw/' . $wscid . '.json';
        if (!file_exists($path)) {
            return null;
        }
        return json_decode(file_get_contents($path), true);
    }

    /** ISO-8601 timestamp string, or null if file doesn't exist. */
    public function lastUpdated(): ?string
    {
        $path = $this->dataDir . '/last_updated.txt';
        return file_exists($path) ? trim(file_get_contents($path)) : null;
    }

    // -----------------------------------------------------------------------
    // Helpers for determining primary role
    // -----------------------------------------------------------------------

    /**
     * Determine the primary role of a dancer ('leader'|'follower'|null).
     *
     * Primary = role with higher required division.
     * Tie-break = role with more total points across all divisions.
     */
    public function primaryRole(array $dancer): ?string
    {
        $l = $dancer['leader']   ?? null;
        $f = $dancer['follower'] ?? null;

        if ($l === null && $f === null) {
            return null;
        }
        if ($l === null) {
            return 'follower';
        }
        if ($f === null) {
            return 'leader';
        }

        $lRequired = $l['level']['required'] ?? $this->inferRequired($l['points'] ?? []);
        $fRequired = $f['level']['required'] ?? $this->inferRequired($f['points'] ?? []);

        $lRank = self::DIV_ORDER[$lRequired ?? ''] ?? 99;
        $fRank = self::DIV_ORDER[$fRequired ?? ''] ?? 99;

        if ($lRank < $fRank) {
            return 'leader';   // lower index = higher division
        }
        if ($fRank < $lRank) {
            return 'follower';
        }

        // Tie-break: total points
        $lPts = array_sum($l['points'] ?? []);
        $fPts = array_sum($f['points'] ?? []);

        return $lPts >= $fPts ? 'leader' : 'follower';
    }

    /** Full name from a role entry, falling back to csv_name. */
    public function fullName(array $dancer): string
    {
        foreach (['leader', 'follower'] as $role) {
            $r = $dancer[$role] ?? null;
            if ($r) {
                $first = $r['first_name'] ?? '';
                $last  = $r['last_name']  ?? '';
                if ($first || $last) {
                    return trim($first . ' ' . $last);
                }
            }
        }
        return $dancer['csv_name'] ?? 'Unknown';
    }

    public static function divisions(): array
    {
        return self::DIVISIONS;
    }

    public static function divOrder(): array
    {
        return self::DIV_ORDER;
    }

    /**
     * Infer the required (mandatory) division from accumulated points using
     * standard WSDC promotion thresholds:
     *   NEW >= 16  → required NOV
     *   NOV >= 30  → required INT
     *   INT >= 45  → required ADV
     *   ADV >= 45  → required ALS
     *   ALS >= 30  → required CHA
     *
     * Falls back to the highest division with any points if no threshold
     * is crossed yet.
     */
    private function inferRequired(array $points): ?string
    {
        // Thresholds: [division whose points are checked => required division if met]
        $thresholds = [
            'ALS' => ['required' => 'CHA', 'min' => 150],
            'ADV' => ['required' => 'ALS', 'min' => 60],
            'INT' => ['required' => 'ADV', 'min' => 45],
            'NOV' => ['required' => 'INT', 'min' => 30],
            'NEW' => ['required' => 'NOV', 'min' => 16],
        ];

        // Check from highest division downward so we return the highest
        // required level first.
        foreach (['ALS', 'ADV', 'INT', 'NOV', 'NEW'] as $div) {
            $pts = (int) ($points[$div] ?? 0);
            if ($pts >= $thresholds[$div]['min']) {
                return $thresholds[$div]['required'];
            }
        }

        // Below all thresholds — use highest division where they have any points.
        foreach (self::DIVISIONS as $div) {
            if ((int) ($points[$div] ?? 0) > 0) {
                return $div;
            }
        }

        return null;
    }
}
